@startuml
title Diagrama de Casos de Uso - Sistema de Biblioteca

actor Estudiante
actor Profesor
actor Bibliotecario
actor Sistema

package "Gestión de Reservar" {
  usecase "Hacer reserva" as UC1
  usecase "Cancelar reserva" as UC2
  usecase "Notificar disponibilidad" as UC3
}

package "Búsqueda y consulta" {
  usecase "Buscar en catálogo" as UC4
  usecase "Ver historial de préstamos" as UC5
  usecase "Consultar estado de libro" as UC6
}


package "Penalizaciones" {
  usecase "Calcular multa" as UC7
  usecase "Pagar multa online" as UC8
  usecase "Aplicar penalización" as UC9
}


package "Reportes" {
  usecase "Generar reporte de préstamos" as UC10
  usecase "Generar reporte de multas" as UC11
}

usecase "Solicitar préstamo" as UC12
usecase "Renovar préstamo" as UC13
usecase "Devolver libro" as UC14
usecase "Procesar devolución" as UC15
usecase "Registrar préstamo manual" as UC16


' Estudiante
Estudiante --> UC12
Estudiante --> UC13
Estudiante --> UC14
Estudiante --> UC1
Estudiante --> UC2
Estudiante --> UC4
Estudiante --> UC5
Estudiante --> UC6
Estudiante --> UC8

' Profesor
Profesor --> UC12
Profesor --> UC13
Profesor --> UC14
Profesor --> UC1
Profesor --> UC2
Profesor --> UC4
Profesor --> UC5
Profesor --> UC6
Profesor --> UC8

' Bibliotecario
Bibliotecario --> UC15
Bibliotecario --> UC16
Bibliotecario --> UC9
Bibliotecario --> UC10
Bibliotecario --> UC11

' Sistema
Sistema --> UC3
Sistema --> UC7

@enduml