@startgantt
title Proyecto FPS Triple A
projectscale monthly

' Configuración de estilos
skinparam backgroundColor white
<style>
gantt {
  task {
    BackgroundColor LightGrey
    LineColor Black
  }
}
</style>

project starts 2025-01-01

[GDD] lasts 20 days
then [PMov] lasts 15 days
then [PCC] lasts 30 days

[DAB] starts at [GDD]'s end lasts 15 days
note bottom: Equipo: 2 Ing. Backend

[ACI] lasts 20 days
[M1] happens at [PCC]'s end
note bottom: Milestone 1: Prototipo

[ISD] starts at [DAB]'s end lasts 60 days
[DMAF] starts at [M1]'s end lasts 45 days
[DCM] starts at [ACI]'s end lasts 120 days
[IM] starts at [ISD]'s end lasts 90 days
note bottom: Librerías especializadas

[CP] starts at [ACI]'s end lasts 90 days
[IUHF] starts at [DMAF]'s end lasts 60 days
[BII] starts at [DMAF]'s end lasts 30 days

[M2] happens at [IM]'s end
note bottom: Milestone 2: Beta

[BC] starts at [M2]'s end lasts 30 days
[PES] starts at [BC]'s end lasts 15 days
[CBP] starts at [BC]'s end lasts 60 days
[PML] lasts 45 days
[DFT] starts at [CBP]'s end lasts 5 days

[M3] happens at [DFT]'s end
note bottom: Milestone 3: v1.0

@endgantt