@startmindmap
+[#Orange] Sky builder
++[#Green] planifica tu ciudad  🧩 
+++[#Yellow] edifica 🏗️
+++[#Yellow]Crea parques 🌳 
+++[#Yellow] diseña carreteras 🛣️
++[#Green] gestiona recursos ⚙️
+++[#Yellow] administra finanzas  💰
+++[#Yellow] optimiza servicios públicos 🔌
++[#Green] interactua con los ciudadanos  🤝
+++[#Yellow] responde a sus necesidades 💬
+++[#Yellow] expande tu territorio 🚀
--[#Green] desafios y misiones 🎯
---[#Yellow] eventos especiales 🌟
---[#Yellow] misiones semanales 📅
---[#Yellow] misiones diarias ⏰
--[#Green] modos de juego 🎮
---[#Yellow] modo libre 🆓
---[#Yellow] modo campaña 📖
---[#Yellow] modo online 🌐
--[#Green] personalizacion 🎨
---[#Yellow] edificos personalizados 🏢
---[#Yellow] avatares personalizados 👤
@endmindmap
