@startjson
title Vaquero Valley - Estructura jugabilidad y organización de datos
{
  "config": {
    "version": "1.0",
    "idioma": "es-ES",
    "autor": "Adrián Martínez",
    "fechaCreacion": "2025-11-08"
  }
  ,
  "clases": {
    "jugador": {
      "id": "J01",
      "nombre": "drictoG",
      "fechaRegistro": "2025-11-08",
      "nivel": 3,
      "puebloId": "P01",
      "activo": true
    }
    ,
    "pueblo": {
      "id": "P01",
      "nombre": "Caserío Colesterol",
      "fecha": "2025-11-08",
      "estado": "activo",
      "propietarioId": "J01",
      "habitantes": 30,
      "edificios": [
      {
        "id": "E01",
        "nombre": "Taberna",
        "estado": "construido",
        "personajes": ["C01"]
      }
      ,
      {
        "id": "E02",
        "nombre": "Oficina del Sheriff",
        "estado": "enConstruccion",
        "nivel": 1,
        "objetos": ["O01"]
      }
      ]
    }
    ,
    "personaje": {
      "id": "C01",
      "nombre": "Arthur",
      "rol": "vaquero",
      "salud": 95,
      "esNpc": true,
      "ubicacionEdificioId": "E01",
      "objetos": ["O01"]
    }
    ,
    "objeto": {
      "id": "O01",
      "nombre": "Revolver",
      "tipo": "arma",
      "danio": 25,
      "fechaCreacion": "2025-11-05",
      "disponible": true
    }
  }
  ,
  "acciones": [
  {
    "nombre": "fundarPueblo",
    "afecta": "pueblo",
    "parametros": ["jugadorId", "nombre", "puebloId"]
  }
  ,
  {
    "nombre": "construirEdificio",
    "afecta": "edificio",
    "parametros": ["puebloId", "nombre"]
  }
  ,
  {
    "nombre": "reclutarPersonaje",
    "afecta": "personaje",
    "parametros": ["puebloId", "nombre", "rol"]
  }
  ,
  {
    "nombre": "asignarObjeto",
    "afecta": "objeto",
    "parametros": ["personajeId", "objetoId"]
  }
  ]
}
@endjson