@startgantt gantt
Project starts 2025-01-01

-- Etapa 1 - Preproducción --
[Construcción del mundo y lore] requires 7 days
then [Arte conceptual de personajes y entornos] requires 8 days
then [Diseño de rutas y decisiones narrativas] requires 10 days
note bottom
  Objetivo: Establecer tono, estética y conflictos del Reino de Elaria.
end note

-- Etapa 2 - Producción --
[Escritura de escenas y diálogos] requires 14 days
then [Creación de sprites y fondos] requires 18 days
then [Implementación en Ren'Py] requires 15 days

-- Etapa 3 - Postproducción --
[Pruebas y correcciones] requires 7 days
then [Mejoras de sonido y efectos visuales] requires 5 days
then [Versión final y exportación] requires 3 days

@endgantt
