@startmindmap
* Mi carrera profesional
right side

** Habilidades
*** Programación (Python, Java, C++)
*** Análisis de datos
*** Trabajo en equipo
** Objetivos
*** Obtener experiencia
*** Liderar proyectos tecnológicos
*** Innovar en el sector teconológico
** Certificaciones
*** Certificado en programación expedido por mi casa

left side
** Experiencia laboral
*** 11000 trofeos de Clash Royale
** Estudios
*** Grado en Ingeniería Informática
*** Bachillerato
*** Grado profesional de música


@endmindmap