@startmindmap
<style>
mindmapDiagram {
  .serviciosStyle * {
    BackgroundColor #fff
  }
  .ocioStyle * {
    BackgroundColor #2f29d8
    FontColor #fff
  }
    .comercioStyle * {
    BackgroundColor #d5d025
  }
    .tranportStyle * {
    BackgroundColor #A0291C
    FontColor #fff
  }
 node {
    FontSize 14
  }
  rootNode {
    BackgroundColor red
    FontColor #fff
    FontSize 18
  }
}
</style>

+ AmeriCity Builder <:1F307:>

-- Servicios Ciudadanos <:1F6A6:> <<serviciosStyle>>
--- Agua <:1F6B0:>
--- Electricidad <:1F4A1:>
--- Saneamiento <:1F6BD:>

++ Ocio y Entretenimiento <:1F57A:> <<ocioStyle>>
+++ Mega Estadios <:1F3DF:>
++++ Futbol Americano
++++ Baseball
+++ Zonas abiertas <:1f333:>
++++ Playas
++++ Campos de Golf
++++ Marinas


-- Transporte <:1F6E3:> <<tranportStyle>>
--- Tipos de vías <:1F686:>
---- Calles suburbanas
---- Stroads
---- Autopistas
---- Freeways
--- Medios <:1F68D:>
---- Coches pequeños
---- Coches grandes
---- Autobuses 
---- Monorieles

++ Comercios <:1F6D2:> <<comercioStyle>>
+++ Compras <:1F4B0:>
++++ Walmart
++++ Costco
++++ Buccees
++++ Strip Malls
+++ Restaurantes <:1F374:>
++++ Estilo "To-Go"
++++ Servicio de mesa
@endmindmap